{% set name = "jiter" %}
{% set version = "0.16.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b24c3492c5f4f84a37946ad9cf504910cf6a782d6a4e0689b6673c5894b4a1c

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.9.4,<2
    - pip
  run:
    - python

test:
  source_files:
    - crates/jiter-python/tests
    - crates/jiter/benches
  imports:
    - jiter
  requires:
    - pip
    - pytest
    - dirty-equals
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv crates/jiter-python/tests

about:
  home: https://crates.io/crates/jiter
  summary: Fast iterable JSON parser.
  description: Fast iterable JSON parser.
  license: MIT
  license_file:
    - LICENSE
    - crates/jiter-python/LICENSE
    - crates/jiter/LICENSE
  license_family: MIT
  doc_url: https://docs.rs/jiter/latest/jiter
  dev_url: https://github.com/pydantic/jiter

extra:
  recipe-maintainers:
    - jan-janssen
  skip-lints:
    - reachable_url
