{% set name = "jiter" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jiter-{{ version }}.tar.gz
  sha256: 29b9d44f23f0c05f46d482f4ebf03213ee290d77999525d0975a17f875bf1eea

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1,<2
    - pip
  run:
    - python

test:
  imports:
    - jiter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://crates.io/crates/jiter
  summary: Fast iterable JSON parser.
  license: MIT
  license_file: crates/jiter/LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
